---
title: "READi report"
output: 
    html_document
params:
    p1_input: 
    bias_input: NA
    p3_input: NA
---


```{r setup, include=FALSE}
library(plotly)
library(gt)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)


biasPlotFunction <- function(phase1_inputs, bias_values){
  if (is.null(bias_values())){
    return()
  }
  
  # -- creating dummy df to merge to primary or secondary outcomes (to account for 0 values in count)
  resp <-  c("Low Risk of Bias", "Moderate Risk of Bias", "High Risk of Bias", "Unclear Reporting")
  
  df_dummy <- data.frame(     # using variable convention of table() to bind and then account for 0s (table won't show 0 count values, obviously)
    responses =  factor(resp, levels = resp, ordered = TRUE),
    Freq = c(rep(0,4))
  )
  
  
  
  bias <- reactiveValuesToList(bias_values())
  
  
  # -- Answers to the Standard Question at the end of all individual study evals
  x <- unlist(lapply(seq_len(length(bias)), function(i){bias[[as.character(i)]]$standard_bias})) # unlisting answers from individualStudyEval (found in bias <- reactiveValuesToList(bias_values()))
  
  # -- "Does this apply to your primary outcome"
  y <- unlist(lapply(seq_len(length(bias)), function(i){bias[[as.character(i)]]$outcome1}))
  
  if (phase1_inputs$t1_outcomes == 1){
    
    # -- we want all values to show up regardless if they have been selected, so we need to count them here and give 0 to all without values
    # -- additionally, we only want the responses applicable to outcome 1 (if y = "Yes", from above)
    df_responses <- data.frame(x = x, y = y) 
    responses <- df_responses$x[df_responses$y == "Yes"]
    
    
    x <- data.frame(table(responses))   # counting all responses in x
    
    
    df_full <- rbind(x, df_dummy) %>% # create and sum df_full - all counts should be there regardless of 0 or non-zero
      mutate(total_count = sum(Freq)) %>% 
      group_by(responses) %>% 
      summarise(pct = sum(Freq)/max(total_count))
    
  
    
    
    bias_plot <- plot_ly(df_full,
                         x = ~responses,
                         y = ~pct,
                         type = "bar",
                         marker = list(color = c('rgba(51,0,111,0.8)', 'rgba(232,211,162,0.8)',
                                                 'rgba(216,217,218,1)', "black")),
                         hovertemplate = paste("Response: %{x} <br> Share of Responses: %{y}")) %>% 
      layout(title = paste0("Summary of Responses for the Primary Outcome of",  phase1_inputs$t1_poutcome),
             yaxis = list(title = 'Percent', tickformat = '.0%',range = c(0,1)),
             xaxis = list(title = '',
                          categoryorder = "array",
                          categoryarray = c("Low Risk of Bias", "Moderate Risk of Bias", "High Risk of Bias", "Unclear Reporting"))) %>% 
      config(displayModeBar = FALSE, displaylogo = FALSE)
    
    return(bias_plot)
    
  } else {
    
    z <- unlist(lapply(seq_len(length(bias)), function(i){bias[[as.character(i)]]$outcome2}))
    
    # -- gathering all the primary data
    df_responses_primary <- data.frame(x = x, y = y)
    responses_primary <- df_responses_primary$x[df_responses_primary$y == "Yes"]
    df_primary <- data.frame(table(responses_primary)) %>% 
      select(responses = responses_primary, Freq)
    
    df_first <- rbind(df_primary, df_dummy) %>% 
      mutate(total_count = sum(Freq)) %>% 
      group_by(responses) %>% 
      summarise(pct1 = sum(Freq)/max(total_count))
    
    # -- gathering all the secondary data
    df_responses_secondary <- data.frame(x = x, y = z)
    responses_secondary <- df_responses_secondary$x[df_responses_secondary$y == "Yes"]
    df_secondary <- data.frame(table(responses_secondary)) %>% 
      select(responses = responses_secondary, Freq)
    
    df_second<- rbind(df_secondary, df_dummy) %>% 
      mutate(total_count = sum(Freq)) %>% 
      group_by(responses) %>% 
      summarise(pct2 = sum(Freq)/max(total_count))
    
    final <- merge(df_first, df_second)
    
    
    bias_plot <- plot_ly(final,
                         x = ~responses,
                         y = ~pct1,
                         type = "bar",
                         marker = list(color = c('rgba(51,0,111,0.8)')),
                         name = "Primary",
                         hovertemplate = paste("Outcome: Primary <br> Response: %{x} <br> Share of Responses: %{y}")) %>% 
      layout(title = paste0("Summary of Responses for the Outcomes of ", phase1_inputs$t1_poutcome," and ", phase1_inputs$t1_soutcome),
             yaxis = list(title = 'Percent', tickformat = '.0%',range = c(0,1)),
             xaxis = list(title = '')) %>% 
      add_trace(
        x = ~responses,
        y = ~pct2,
        type = "bar",
        hovertemplate = paste("Outcome: Secondary <br> Response: %{x} <br> Share of Responses: %{y}"),
        marker = list(color = c('rgba(232,211,162,0.8)')),
        name = "Secondary"
      ) %>% 
      config(displayModeBar = FALSE, displaylogo = FALSE)
    
  }
    
    return(bias_plot)
}
table_function <- function(phase1_inputs, phase3_inputs){
  domain_vec <- c("Comparator in each study", 
                  "Number of studies and number of subjects (overall)",
                  "Level of overall study limitation",
                  "Are the results consistent",
                  "Are the results direct?",
                  "Are the results precise?",
                  "Is there publication bias?")

  if (!is.null(phase3_inputs$t3_comparator_1) && !is.null(phase3_inputs$t3_subjects_1)) {
    if (phase1_inputs$t1_outcomes == 1){
      outcomes <- c(phase3_inputs$t3_comparator_1,
                    phase3_inputs$t3_subjects_1,
                    phase3_inputs$t3_studylim_1,
                    phase3_inputs$t3_consistent_1,
                    phase3_inputs$t3_direct_1,
                    phase3_inputs$t3_precise_1,
                    phase3_inputs$t3_bias_1)
      df <- data.frame(
        Domains = domain_vec,
        Responses = outcomes,
        type = rep(phase1_inputs$t1_poutcome, 7)) %>%
        group_by(type)
    } else {
      outcomes <- c(phase3_inputs$t3_studylim_1,
                    phase3_inputs$t3_subjects_1,
                    phase3_inputs$t3_comparator_1,
                    phase3_inputs$t3_consistent_1,
                    phase3_inputs$t3_direct_1,
                    phase3_inputs$t3_precise_1,
                    phase3_inputs$t3_bias_1,
                    phase3_inputs$t3_studylim_2,
                    phase3_inputs$t3_subjects_2,
                    phase3_inputs$t3_comparator_2,
                    phase3_inputs$t3_consistent_2,
                    phase3_inputs$t3_direct_2,
                    phase3_inputs$t3_precise_2,
                    phase3_inputs$t3_bias_2)
      df <- data.frame(
        Domains   = rep(domain_vec,2),
        Responses = outcomes,
        type = c(rep(phase1_inputs$t1_poutcome, 7),rep(phase1_inputs$t1_soutcome,7))) %>%
        group_by(type)
    }
    return(df)
  }
}


```

## READi
Real-World Evidence Assessments and Needs Guidance

**Population:** `r params$p1_input$t1_pop_interest`\
**Intervention:** `r params$p1_input$t1_int_interest`\
**Comparator:** `r params$p1_input$t1_comparator`\
**Outcome:** `r params$p1_input$t1_poutcome`\
**Time frame:** `r params$p1_input$t1_timeframe`\
**Setting:** `r params$p1_input$t1_setting`\


```{r}
 
biasPlotFunction(params$p1_input, params$bias_input)
table_function(params$p1_input, params$p3_input) %>%
    gt(rowname_col = "Domains") %>%
    tab_header(title = "Whole Body of Evidence Review",
               subtitle = md("*For each outcome of interest*")) %>%
    tab_options(
      row_group.background.color = "#FFEFDB80",
      heading.background.color = "#E8DCF0"
    )

```



