homePageUI <- bootstrapPage(
    div(id = "home", class = "jumbotron",
        img(src = "CHOICE.png", id = "choice-image"),
        h2("Welcome to the REAdi (Real-World Evidence Assessments and Needs Guidance) Tool"),
        h3(id = "author", "presented by The CHOICE Institute"),
        tagList(a(icon("github", "fa-2x"), href = "https://github.com/btbeal/READi", 
                  target = "_blank")),
        hr(),
        p("The REAdi Tool is a comprehensive online tool to guide literature review and coverage decision-making"),
        p("Once you have decided you need real world evidence to answer your question of interest, the READi tool 
                                        will guide you through a 3-Phase processs of evaluating the literature to inform your adoption decision."),
        a(class = "btn btn-primary btn-lg", `data-toggle` = "collapse", href ="#collapse-detail", role = "button", "Learn more", id = "learn"),
        div(class = "collapse", id = "collapse-detail",
            bsCollapse(id = "accordion",
                       bsCollapsePanel("Phase 1: Identifying RWE", div(class = "card-body", 
                                                        h4("Identifying Real World Evidence"),
                                                        hr(),
                                                        p("Phase 1 is all about identifying the available evidence to address the question at hand. Here, you'll be guided through a list of questions using the PICOT format in order to generate a pubmed search string."),
                                                        p("The search generated by this phase of the process will probably give you the most accurate results; however, feel free to complete this step outside of the app using PubMed. Note that if you choose to do identify your literature this way, 
                                                          you will still need to complete and submit Phase 1 to move on to the subsequent phases."))),
                       bsCollapsePanel("Phase 2: Reviewing and Grading RWE", div(class = "card-body",
                                                        h4("Reviewing and Grading Evidence"),
                                                        hr(),
                                                        p("This phase assumes you have conducted your literature search and have identified your studies of interest from Phase 1 (or an outside source). Once Phase 1 is completed,
                                                          Phase 2 will help you grade each of your studies based on the appropriate tool identified for the given study type. By the end of this phase, you will have given each of your pieces of literature
                                                          a summary score to be aggregated in Phase 3."))),
                       bsCollapsePanel("Phase 3: Summarizing Your Graded Evidence", div(class = "card-body", 
                                                        h4("Summarizing Your Graded Evidence"),
                                                        hr(),
                                                        p("By the time you're in Phase 3, you've already done most of the work. Here in Phase 3, you will be asked to take a look at a summary of your ratings from Phase 2,
                                                          then provide an overall score of the entire body of literature you've identified. You'll include things such as bias, consistency, and precision for the total body of evidence and for each of your outcomes. Once this section is complete, you'll be prepared for stage 4: providing a recommendation."))),
                       bsCollapsePanel("Phase 4: Developing an Evidence-Based Recommendation", div(class = "card-body",
                                                        h4("Developing an Evidence-Based Recommendation"),
                                                        hr(),
                                                        p("Phase 4 is the final step, and the ultimate goal of this entire process: providing an evidence-based recommendation. Here, 
                                                          you'll consider the rating of the entire body of evidence for the proposed intervention, then provide a recommendation based on that consideration.
                                                          There will be multiple choices to consider as well as practical implementation concerns to help you think about this. Finally, upon completion of this phase,
                                                          you will have a PDF of your process available for printing."))))),
                               hr(),
        actionButton(inputId = "beginPhase", label = "Click here when you're ready to begin!")
    
    
    ))