graceUI <- function(id){
  ns <- NS(id)
  
  wellPanel(id = "Grace",
            strong("1B. Please rate the quality of the study using the GRACE Checklist."),
            br(),
            tagList(a("GRACE: Good ReseArch for Comparative Effectiveness", href="https://www.graceprinciples.org/grace.html", target = "_blank"),
                    br(),
                    br(),
                    
                    h4("Data"),
                    wellPanel(strong("D1. Were treatment and/or important details of treatment exposure adequately recorded for the purpose in the data source?"),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace1_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes - reasonably necessary information to determine treatment or intervention was adequately recorded for study purposes (e.g., for drugs, sufficient detail on dose, days supplied, route or other data important. For vaccines, consider the importance of batch, dose, route and site of administration, etc. For devices, consider type of device, placement, surgical procedure used, serial number, etc.)",
                                                                "No - data source clearly deficient or not enough information in article"),
                                                    selected = "No - data source clearly deficient or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace1_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("D2. Were the primary outcomes adequately recorded for the study purpose (e.g., available in sufficient detail through data source(s))?"),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace2_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes -  information to ascertain outcomes were adequately recorded in the data source (e.g., if clinical outcomes were ascertained using ICD-9/ICD-10 diagnosis code(s) in an administrative database, the level of sensitivity and specificity captured by the code(s) was sufficient for assessing the outcome of interest.)",
                                                                "No - data source clearly deficient (e.g., the code(s) captured a range of conditions that was too broad or narrow, and supplementary information such as that from medical charts was not available), or not enough information in article"),
                                                    selected = "No - data source clearly deficient (e.g., the code(s) captured a range of conditions that was too broad or narrow, and supplementary information such as that from medical charts was not available), or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace2_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("D3. Was the primary clinical outcome(s) measured objectively rather than subject to clinical judgment (e.g., opinion about whether the patient’s condition has improved)?"),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace3_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes - clinical outcomes were measured objectively (e.g., hospitalization, mortality)",
                                                                "N/A - primary outcome not clinical (e.g. PROs)",
                                                                "No - e.g., clinical opinion about whether patient's condition improved, or not enough information in article"),
                                                    selected = "No - e.g., clinical opinion about whether patient's condition improved, or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace3_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("D4. Were primary outcomes validated, adjudicated, or otherwise known to be valid in a similar population?"),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace4_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes - outcomes were validated, adjudicated, or based on medical chart abstractions with clear definitions, e.g. a validated instrument was used to assess patient-reported outcomes (e.g., SF-12 Health Survey); a clinical diagnosis via ICD-9 code was used, with formal medical record adjudication by committee to confirm diagnosis or other procedures to achieve reasonable sensitivity and specificity; billing data were used to assess health resource utilization, etc.",
                                                                "No, or not enough information in article"),
                                                    selected = "No, or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace4_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("D5. Was the primary outcome(s) measured or identified in an equivalent manner between the treatment/intervention group and the comparison group(s)?"),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace5_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes",
                                                                "No, or not enough information in article"),
                                                    selected = "No, or not enough information in article)"),
                                column(4,
                                       textAreaInput(inputId = ns("grace5_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("D6. Were important covariates that may be known confounders or effect modifiers available and recorded? Important covariates depend on the treatment and/or outcome of interest, (e.g., body mass index should be available and recorded for studies of diabetes; race should be available and recorded for studies of hypertension and glaucoma)."),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace6_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes - most if not all important known confounders and effect 
                                                                 modifiers available and recorded, e.g., measures of medication 
                                                                 dose and duration.",
                                                                "No  - at least one important known confounder or effect modifier not 
                                                                available and recorded (as noted by authors or as determined by user's 
                                                                clinical knowledge), or not enough information in article"),
                                                    selected = "No  - at least one important known confounder or effect modifier not 
                                                                available and recorded (as noted by authors or as determined by user's 
                                                                clinical knowledge), or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace6_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    br(),
                    br(),
                    br(),
                    h4("Methods"),
                    wellPanel(strong("M1. Was the study (or analysis) population restricted to new initiators of treatment or those starting a new course of treatment? Efforts to include only new initiators may include restricting the cohort to those who had a washout period (specified period of medication nonuse) prior to the beginning of study follow-up."),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace7_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes - only new initiators of the treatment of interest were included in the cohort, or for surgical procedures and devices, only patients who never had the treatment before the start of study follow-up were included.",
                                                                      "No, or not enough information in article"),
                                                    selected = "No, or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace7_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("M2. If one or more comparison groups were used, were they concurrent comparators? If not, did the authors justify the use of historical comparisons group(s)?"),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace8_yes"), 
                                                    label =  NULL, 
                                                    choices = c("Yes - data were collected during the same time period as the treatment group (“concurrent”) or historical comparators were used with reasonable justification, e.g., when it is impossible for researchers to identify current users of older treatments or when a concurrent comparison group is not valid—(i.e., uptake of new product is so rapid that concurrent comparators differ greatly on factors related to the outcome)",
                                                                "No - historical comparators used without being scientifically justifiable, or not enough information in article"),
                                                    selected = "No - historical comparators used without being scientifically justifiable, or not enough information in article"))),
                                column(4,
                                       textAreaInput(inputId = ns("grace8_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("M3. Were important covariates, confounding and effect modifying variables taken into account in the design and/or analysis?Appropriate methods to take these variables into account may include: restriction, stratification, interaction terms, multivariate analysis, propensity score matching, instrumental variables or other approaches."),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace9_yes"), 
                                                    label =  NULL,
                                                    choices = c("Yes - most if not all important covariates that would be likely to change the effect estimate substantially were accounted for, e.g., measures of medication dose and duration.",
                                                                "No - some important covariates were available for analysis but not analyzed appropriately, or at least one important covariate was not measured, or not enough information in article"),
                                                    selected = "No - some important covariates were available for analysis but not analyzed appropriately, or at least one important covariate was not measured, or not enough information in article"))),
                                column(4,
                                       textAreaInput(inputId = ns("grace9_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("M4. Is the classification of exposed and unexposed person-time free of “immortal time bias”? Immortal time in epidemiology refers to a period of cohort follow-up time during which death (or an outcome that determines end of follow-up) cannot occur."),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace10_yes"), 
                                                          label =  NULL,
                                                          choices = c("Yes",
                                                                      "No, or not enough information in article"),
                                                          selected = "No, or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace10_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))),
                    wellPanel(strong("M5. Were any meaningful analyses conducted to test key assumptions on which primary results are based? E.g., were some analyses reported to evaluate the potential for a biased assessment of exposure or outcome, such as analyses where the impact of varying exposure and/or outcome definitions was tested to examine the impact on results."),
                              br(),
                              br(),
                              fluidRow(
                                column(8, 
                                       radioButtons(inputId = ns("grace11_yes"), 
                                                    label =  NULL,
                                                    choices = c("Yes - and primary results did not substantially change",
                                                                "Yes - and primaary results changed substantially",
                                                                "None reported, or not enough information in article"),
                                                    selected = "None reported, or not enough information in article")),
                                column(4,
                                       textAreaInput(inputId = ns("grace11_text"), 
                                                     label = NULL,
                                                     height = "400%",
                                                     placeholder = "Comments:")))))
}


grace <- function(input, output, session){
  ns <- session$ns
  
}